set nocompatible 
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'L9'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'
Bundle 'Valloric/YouCompleteMe'
Bundle 'Valloric/ListToggle'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/syntastic'
Bundle 'vim-scripts/taglist.vim'
Bundle 'vim-scripts/cscope.vim'
Bundle 'vim-scripts/winmanager'
Bundle 'vim-scripts/minibufexplorerpp'
call vundle#end()


filetype plugin indent on
syntax enable on 
set nu
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set hlsearch
set smartindent
set cursorline
map <C-n> :NERDTreeToggle<CR>

"set Solarized
syntax enable
colorscheme solarized
if has('gui_running')
    set background=light
else
    set background=dark
endif

"set ctags
map <C-R> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

"set taglist
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

"set Cscope
set cscopequickfix=s-,c-,d-,i-,t-,e- 
nmap <C-_>s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>c :cs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>t :cs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>e :cs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-_>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
nmap <C-_>i :cs find i <C-R>=expand("<cfile>")<CR><CR>
nmap <C-_>d :cs find d <C-R>=expand("<cword>")<CR><CR>

"set winmanager
let g:NERDTree_title="[NERDTree]"  
let g:winManagerWindowLayout="NERDTree|TagList"  
  
function! NERDTree_Start()  
	exec 'NERDTree'  
endfunction  
	  
function! NERDTree_IsValid()  
    return 1  
endfunction  

nmap wm :WMToggle<CR>


"set vim-scripts/minibufexplorerpp
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapWindowNavVim = 1   
let g:miniBufExplMapCTabSwitchBufs = 1   
let g:miniBufExplModSelTarget = 1  
let g:miniBufExplMoreThanOne=0

"set YouCompleteMe
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'   "配置默认的ycm_extra_conf.py
let g:ycm_confirm_extra_conf=0    "打开vim时不再询问是否加载ycm_extra_conf.py配置
let g:ycm_collect_identifiers_from_tag_files = 1 "使用ctags生成的tags文件

syntax on
